enabled: true

fullNameOverride: goproxy

replicaCount: 1

image:
  repository: registry.hub.docker.com/goproxy/goproxy
  pullPolicy: Always
  tag: latest

readinessProbe:
  tcpSocket:
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  tcpSocket:
    port: 8081
  initialDelaySeconds: 15
  periodSeconds: 20

podSecurityContext: {}

containerSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

rbac:
  pspEnabled: false

serviceAccount:
  create: false

ingress:
  enabled: false

service:
  type: ClusterIP
  port: 8081
  name: http

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false

serviceMonitor:
  enabled: false

metricsService: {}
nodeSelector: {}
tolerations: {}
annotations: {}
podAnnotations: {}
podDisruptionBudget: {}
securityContext: {}
networkPolicy: {}
topologySpreadConstraints: {}
affinity: {}
config: {}
configContainerPath: {}
imagePullSecrets: {}
