## Reference: https://github.com/helm/chart-testing/blob/master/doc/ct_lint-and-install.md
# Don't add the 'debug' attribute, otherwise the workflow won't work anymore
# Only Used for the CT Install Stage
remote: origin
target-branch: main
chart-dirs:
  - charts
chart-repos:
  - argo=https://argoproj.github.io/argo-helm
  - stable=https://charts.helm.sh/stable
  - incubator=https://charts.helm.sh/incubator
  - roberc7=https://roberc7.github.io/helm-charts
helm-extra-args: "--timeout 1000s"
validate-chart-schema: false
validate-maintainers: true
validate-yaml: true
exclude-deprecated: true
