# https://external-secrets.io/v0.7.2/api/clustersecretstore/
# The ClusterSecretStore is a cluster scoped SecretStore that can be referenced by all ExternalSecrets from all namespaces. Use it to offer a central gateway to your secret backend.
# If you want to design namespace constrained SecretStore you must use SecretStore which do not have this limitation. (see `/templates/secretstore.yaml`)

{{- range $i, $clusterSecretStore := .Values.clusterSecretStores }}
{{- if $clusterSecretStore.enabled }}
---
apiVersion: {{ include "external-secrets.apiVersion" $ }}
kind: ClusterSecretStore
metadata:
  name: {{ $clusterSecretStore.name }}
  labels:
    {{- include "external-secrets.labels" $ | nindent 4 }}
  {{- with $clusterSecretStore.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $clusterSecretStore.annotations }}
  {{- with $clusterSecretStore.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  {{- with $clusterSecretStore.retrySettings }}
  retrySettings:
  {{- toYaml $clusterSecretStore.retrySettings | nindent 4 }}
  {{- end }}
  {{- with $clusterSecretStore.controller }}
  controller:
  {{- toYaml $clusterSecretStore.controller | nindent 4 }}
  {{- end }}
  {{- with $clusterSecretStore.provider }}
  provider:
  {{- toYaml $clusterSecretStore.provider | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
