# https://external-secrets.io/v0.7.2/api/externalsecret/
# The ExternalSecret describes what data should be fetched, how the data should be transformed and saved as a `Kind=Secret`.

{{- range $i, $externalSecret := .Values.externalSecrets }}
{{- if $externalSecret.enabled }}
---
apiVersion: {{ include "external-secrets.apiVersion" $ }}
kind: ExternalSecret
metadata:
  name: {{ $externalSecret.name }}
  namespace: {{ include "external-secrets.namespace" $ }}
  labels:
    {{- include "external-secrets.labels" $ | nindent 4 }}
  {{- with $externalSecret.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $externalSecret.annotations }}
  {{- with $externalSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  {{- if $externalSecret.refreshInterval }}
  refreshInterval: {{ $externalSecret.refreshInterval }}
  {{- end }}
  secretStoreRef:
    name: {{ $externalSecret.secretStoreRef.name }}
    kind: {{ $externalSecret.secretStoreRef.kind }}
  {{- if $externalSecret.target }}
  target:
  {{- toYaml $externalSecret.target | nindent 4 }}
  {{- end }}
  {{- if $externalSecret.data }}
  data:
  {{- toYaml $externalSecret.data | nindent 4 }}
  {{- end}}
  {{- if $externalSecret.dataFrom }}
  dataFrom:
  {{- toYaml $externalSecret.dataFrom | nindent 4 }}
  {{- end}}
{{- end }}
{{- end }}