# https://external-secrets.io/v0.7.2/api/secretstore/
# The SecretStore is namespaced and specifies how to access the external API. The SecretStore maps to exactly one instance of an external API.
# By design, SecretStores are bound to a namespace and can not reference resources across namespaces. 
# If you want to design cross-namespace SecretStores you must use ClusterSecretStores which do not have this limitation. (see `/templates/clustersecretstore.yaml`)

{{- range $i, $secretStore := .Values.secretStores }}
{{- if $secretStore.enabled }}
---
apiVersion: {{ include "external-secrets.apiVersion" $ }}
kind: SecretStore
metadata:
  name: {{ $secretStore.name }}
  namespace: {{ include "external-secrets.namespace" $ }}
  labels:
    {{- include "external-secrets.labels" $ | nindent 4 }}
  {{- with $secretStore.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $secretStore.annotations }}
  {{- with $secretStore.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  {{- with $secretStore.retrySettings }}
  retrySettings:
  {{- toYaml $secretStore.retrySettings | nindent 4 }}
  {{- end }}
  {{- with $secretStore.controller }}
  controller:
  {{- toYaml $secretStore.controller | nindent 4 }}
  {{- end }}
  {{- with $secretStore.provider }}
  provider:
  {{- toYaml $secretStore.provider | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
