{{ $global := . }}
{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservice-basic.fullname" . }}-config
  namespace: {{.Values.namespace}}
data:
  config.json: |-
    {{ .Values.config | toJson }}
{{- end }}