{{ $global := . }}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microservice-basic.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservice-basic.labels" . | nindent 4 }}
  {{- with or (.Values.serviceAccount.annotations) (.Values.serviceAccount.roleArn) }}
  annotations:
    {{- if $.Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- else }}
    eks.amazonaws.com/role-arn: {{ $.Values.serviceAccount.roleArn }}
    {{- end }}
  {{- end }}
{{- end }}