name: Helm Documentation Linting & Generating
on:
  push:
    branches:
      - "main"

permissions: {}

jobs:
  lint-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      BRANCH_NAME: ${{ github.head_ref }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders

      - name: Check All Chart README.md's
        run: ./scripts/helm-docs.sh

      - name: Push to protected branch
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          unprotect_reviews: false
