name: Chart Packaging

on:
  push:
    branches:
      - main

permissions: {}
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "src"
          fetch-depth: 0

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "dest"
          ref: "gh-pages"
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add dependency chart repos
        run: |
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add prometheus https://prometheus-community.github.io/helm-charts
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add hashicorp https://helm.releases.hashicorp.com
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo add roberc7 https://raw.githubusercontent.com/roberc7/helm-charts/gh-pages/ --username roberc7 --password ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm Charts
        shell: bash
        run: |
          find src/charts/ -type f -name 'Chart.yaml' | sed -r 's|/[^/]+$||' | sort | uniq | xargs -L 1 helm dep up
          for d in src/charts/*/ ; do
              echo "$d"
              helm package "$d" -u -d dest
          done

      - name: Push New Files
        shell: bash
        working-directory: dest
        run: |
          helm repo index . --url https://raw.githubusercontent.com/roberc7/helm-charts/gh-pages/
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add $(git ls-files -o --exclude-standard)
          git add index.yaml
          git commit -m "chore(chart-releaser): Uploaded packaged charts from $GITHUB_SHA"
          git push
